FROM <%- baseImage %>
USER root

RUN yum update -y

<% _.forEach(dependencies, function(dependency) { %>
RUN yum install -y <%- dependency %>
<% }); %>

# CentOs don't have lzip in their repo.
RUN wget http://download.savannah.gnu.org/releases/lzip/lzip-1.18.tar.gz -P /tmp
RUN cd /tmp && \
      tar -zxvf lzip-1.18.tar.gz && \
      cd lzip-1.18 && \
      ./configure && \
      make && \
      make install

COPY dependencies.sh /tmp/
RUN /bin/bash -c /tmp/dependencies.sh

RUN useradd -ms /bin/bash tester

USER tester
WORKDIR /home/tester
RUN mkdir /home/tester/sdm

VOLUME /home/tester/sdm

COPY executeTest.sh /tmp/

# For systemd usage this changes to /usr/sbin/init
# Keeping it as /bin/bash for compatability with previous
CMD ["/bin/bash"]
