FROM <%- baseImage %>
USER root

RUN apt update

<% _.forEach(dependencies, function(dependency) { %>
RUN apt install -y <%- dependency %>
<% }); %>

COPY dependencies.sh /tmp/
RUN /bin/bash -c /tmp/dependencies.sh

RUN useradd -ms /bin/bash tester

USER tester
WORKDIR /home/tester
RUN mkdir /home/tester/sdm

VOLUME /home/tester/sdm

COPY executeTest.sh /tmp/

# For systemd usage this changes to /usr/sbin/init
# Keeping it as /bin/bash for compatability with previous
CMD ["/bin/bash"]
